name: build-and-test

on:
  workflow_dispatch:
    inputs:
      pull_request:
        type: string
        required: true
        description: The PR number.
      token:
        type: string
        required: true
        description: The token to use for testing. Short lived.
      uri:
        type: string
        required: true
        description: The uri to test against. Short lived.

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Fork based /LGTM checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.inputs.pull_request }}/merge"

      - name: Run tests on DEVELOP branch
        env:
          API_URL: ${{ secrets.URI }}
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          INPUT_API_URL: ${{ github.event.inputs.uri }}
          INPUT_ACCESS_TOKEN: ${{ github.event.inputs.token }}
        run: |
          echo "env variables for DEVELOP have been set"
          echo "Changing directory into sdk directory"
          echo URI $API_URL
          echo TOKEN $ACCESS_TOKEN
          echo INPUT_URI $INPUT_API_URL
          echo INPUT_TOKEN $INPUT_ACCESS_TOKEN
          echo
          echo
          cat README.md
