name: build-and-test

on:
  workflow_dispatch:
    inputs:
      pull_request:
        type: string
        required: true
        description: The PR number.

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    environment: "PR-${{ github.event.inputs.pull_request }}"

    steps:
      - name: Checkout for SHA
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.inputs.pull_request }}/head"

      - name: Get SHA
        id: vcs
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Fork based /LGTM checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.inputs.pull_request }}/merge"

      - name: Check Run in progress
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const date = new Date();
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: "${{ steps.vcs.outputs.sha }}",
              name: "Integration Testing",

              started_at: date.toISOString(),
              external_id: "${{ github.run_id }}",
              status: "in_progress",

              output: {
                title: "Integration Test Results",
                summary: "Build started",
                text: "Just gonna do stuff ya know."
              }

            });

      - name: Run tests on DEVELOP branch
        id: run_tests
        run: |
          set -e
          echo "env variables for DEVELOP have been set"
          echo "Changing directory into sdk directory"
          echo
          echo Get portfolios
          curl -X GET "${INPUT_API_URL}/api/portfolios" -H  "accept: text/plain" -H  "Authorization: Bearer ${INPUT_ACCESS_TOKEN}" -kL
          echo
          cat README.md
        env:
          INPUT_API_URL: ${{ secrets.URI }}
          INPUT_ACCESS_TOKEN: ${{ secrets.TOKEN }}

      - name: Complete check run
        if: always()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const date = new Date();
            const resp = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: "${{ github.run_id }}"
            });

            const URL = resp.data.jobs[0].html_url

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: "${{steps.vcs.outputs.sha}}",
              name: "Integration Testing",

              completed_at: date.toISOString(),

              external_id: "${{ github.run_id }}",
              details_url: resp.data.jobs[0].html_url,
              status: "completed",
              conclusion: "${{steps.run_tests.conclusion}}",

              output: {
                title: "Integration Tests",
                summary: "Build completed with ${{steps.run_tests.conclusion}}",
                text: `Visit the link to see the result of this step. ${URL}`
              }
            });
